logging:
  level:
    root: INFO
spring:
  application:
    name: elastic-query-web-client-2
  profiles:
    active: elastic_query_web_2
  cloud:
    config:
      name: elastic-query-web-client-2,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
      password: '{cipher}9086a0ea99acdf75cf99f7f66b6136940a4a807c5e666347752d8827888bfb9fa95c583cde89f81a690b62f831452992'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: elastic-query-web-client-2