server:
  port: 8888
logging:
  level:
    root: info
    org.springframework.cloud.config: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Olderrest/spring-cloud-config-server-repository
          clone-on-start: true
          username: Olderrest
          password: '{cipher}61cab60e9250811b94cf11933a44e4eb574e2351d0532cac9b604970ff37d36ed0f0855af52f6987a0dd6059e981c5b1a49ab44ba1a1c3af0d3aa85dcd8cebf9'
        default-label: master
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}9dccd9168b2ec9712f45bcb73dc171c72a96283e8339be21aa59aa3020763baa633b3cf93f9c0734f64df4ce4d6eea50'
encrypt:
  key: ${ENCRYPT_KEY}

log:
  app-name: config-server